[rdy] Move checkFacilities to PlayerHospital
CorsixTH/CorsixTH pull request #1717
Opened 2020-09-20 14:19 UTC by Alberth289346

*Fixes emptiness of player hospital

**Describe what the proposed change does**
- Moved an advise function from `Hospital` and `PlayerHospital`, and cleaned it up.

In more detail:
- All the functions that merely selected and said an advice removed (called from 1 location and not long)
- A lot of flags were useless, as the advise is given at most once a month (selected by day), and the end of the month cleared the flag again.
- Renamed `checkFacilities` to `daily/monthlyAdvisePlayer`

- Bench checking didn't make much sense.
  - It compared with the entire patient population, rather than directly comparing sitting and standing patients.
  - It just checked at a some point without tracking the general status.
  - Number of benches is quite irrelevant, it only counts whether patients can sit down.

- Drinks had a tougher requirement in the first year.

- Bank balance advise had a (useless) flag in `checkFacilities` so got moved as well. The `cashLow` function had some logic as well, which was merged.

- Added a `sayAdvise` function that deals with message selection.

2020-10-04 09:06 UTC, Alberth289346 commented
Same patch, but in smaller steps, hopefully easier to understand.

2020-10-05 20:03 UTC, lewri requested changes
Those naughty advise/advice comments should be addressed with these (you might have to go through any knock-on effects)

2020-10-05 20:03 UTC, lewri commented on CorsixTH/Lua/hospitals/player_hospital.lua
> +--! Give advise to the player at the end of a month.
```suggestion
--! Give advice to the player at the end of a month.
```

2020-10-06 18:36 UTC, Alberth289346 commented on CorsixTH/Lua/hospitals/player_hospital.lua
> +function PlayerHospital:dailyAdvisePlayer()
Renamed to `dailyAdviceChecks`

2020-10-08 00:51 UTC, TheCycoONE commented
The save version probably needs bumped again. @lewri can you unblock this? Looks ok to me besides the conflicts and the save version.

2020-10-08 11:53 UTC, Alberth289346 commented
Rebased, incremented game version to 146, merged cheats (afterLoad conflict)

2020-10-08 18:56 UTC, lewri approved these changes

2020-10-09 01:29 UTC, merged