[RFC] Working status of game
CorsixTH/CorsixTH pull request #1896
Opened 2021-05-24 16:42 UTC by lewri

*Closes #1884*

**Describe what the proposed change does**
- Adds the game's working status to the readme as suggested.
- I tried to show a little humour again (it usually backfires though)

I don't think I wrote it in US English so point out any writing differences.

2021-05-24 16:49 UTC, lewri commented
I realise this may be longer than what Cyco is generally after. However, my concern if putting it in the Wiki may cause it to decay/be neglected.

2021-05-24 21:48 UTC, TheCycoONE commented
Don't worry about the English. This is largely a UK English game.

2021-05-24 21:52 UTC, TheCycoONE commented
The one thing I would suggest is splitting what's working from the original from features the original never had.

2021-05-25 22:41 UTC, TheCycoONE requested changes

2021-05-25 22:41 UTC, TheCycoONE commented on README.md
>  - Single player modes (Campaigns, custom levels, custom campaigns)
The original game did not support custom levels or custom campaigns, those are BIG features of CorsixTH

2021-05-25 22:41 UTC, TheCycoONE commented on README.md
>  - Micromanagement
Micromanagement isn't clear?

2021-05-25 22:41 UTC, TheCycoONE commented on README.md
>  - Full HD resolution and beyond!
Our hidpi support is kinda poor, best to leave this at just widescreen or full HD support?

2021-05-25 22:41 UTC, TheCycoONE commented on README.md
>  - Full control over all hotkeys
Zoom is another big feature we have over the original, deserves mention.

2021-05-26 12:27 UTC, merged