Implement zoom using scaled SDL_RenderCopy.
CorsixTH/CorsixTH pull request #1921
Opened 2021-06-05 15:27 UTC by flackr

This allows removing the zoom texture allocations and removing an intermediate draw to that texture before drawing to the screen noticeably increasing the frame rate which may address issues such as #1420.

2021-06-05 15:56 UTC, tobylane commented
You can ignore this run's error, it's not your changes. I locally generated your PR's documentation fine.

2021-06-05 17:57 UTC, TheCycoONE commented
Rebasing on master will fix the pipeline. The change looks good to me. Will test. Thanks @flackr

2021-06-05 18:27 UTC, TheCycoONE commented
This PR prevents the game from hanging when zooming out on a computer here. Escalating to 0.65.

2021-06-05 18:54 UTC, TheCycoONE commented
There is a regression: on windows you can set the resolution lower than native and then press alt+enter to full screen, which scales the full UI. There is a noticeable reduction in the quality of the result.

2021-06-05 19:10 UTC, flackr commented
I'm a bit confused, is that different than regular zooming out? Or is this a different part of the UI which looks bad? Could you share a screenshot?

I know that `raw_bitmap::draw` has a separate scaling which for best quality we should really be passing forward into `render_target::draw`. I'm not quite sure where raw bitmaps are used or when we set a scaling on them but I can roll that into this change which should eliminate possible additional artifacts there.

2021-06-05 21:10 UTC, TheCycoONE commented
No, not zoom. In windows you can set a lower screen resolution and then switch to full screen and SDL applies a fake full screen by scaling everything on the screen. (Same effect as SDL_RenderSetLogicalSize)

After Patch:
![windows_scale](https://user-images.githubusercontent.com/823433/120905499-68891700-c620-11eb-8c6b-7881fa6e3342.png)

Before:
![windows_scale_old](https://user-images.githubusercontent.com/823433/120905532-ae45df80-c620-11eb-8712-e2301c4dfebf.png)

2021-06-05 21:15 UTC, TheCycoONE commented on CorsixTH/Src/th_gfx_sdl.cpp
>    } else if (eWhatToScale == scaled_items::all && supports_target_textures) {
supports_target_textures should be unnecessary now

2021-06-05 21:23 UTC, TheCycoONE commented
Additionally there are artifacts in the shadows at some zoom levels:
![shadow_artifact](https://user-images.githubusercontent.com/823433/120905813-b4d55680-c622-11eb-88ef-d89abc305f7f.png)

2021-06-05 21:38 UTC, TheCycoONE commented
https://github.com/CorsixTH/CorsixTH/blob/ac4f26df9e54e778cfea257a1f5ba06538f28900/CorsixTH/Src/th_map.cpp#L1008 is where the shadows are rendered, just above is the tiles.

2021-06-05 21:47 UTC, TheCycoONE commented
There is a class of hardware that this patch benefits as is. A cop out, but perhaps it should be a (preferably runtime) flag for now?

2021-06-05 22:59 UTC, flackr commented
Sounds reasonable to me. Then we can incrementally fix the visual artifacts and get it working well on all platforms, but it can benefit users already :-).

Do you have a system for runtime flags / reference to some code I can copy for that?

2021-06-06 03:15 UTC, TheCycoONE commented
We do: https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/config_finder.lua
I can help with that aspect.

2021-06-06 13:06 UTC, TheCycoONE commented
I've pushed the code for setting the runtime option (back to the render_target). Now it's a matter of restoring the old behaviour conditionally. If you're willing, I'll leave that part up to you.

2021-06-06 13:10 UTC, flackr commented
Sounds good, I should have time this afternoon.

2021-06-06 20:47 UTC, flackr commented
I believe this is now properly behind a flag with the zoom texture behavior without it set.

2021-06-07 01:36 UTC, TheCycoONE requested changes
This toggle is in a bit of a limbo as to whether it would support an in game toggle at the moment.

To do so:
- The SDL_SetHint for linear mode in `create` should be moved to an else condition of `if (direct_zoom)` in the `update` function of th_gfx_sdl.cpp.
- global_scale_factor should be reset to 1.0
- All textures would need to be flushed / recreated after the hint is changed. The documentation says that `SDL_HINT_RENDER_SCALE_QUALITY` is applied to a texture at creation rather than at copy (which explains why I didn't see any effect toggling it in set_scale_factor)

If we don't want it to be an in game toggle then this block belongs in the `create` function, either way we only want to set SDL_HINT_RENDER_SCALE_QUALITY in one place (for now - as the feature evolves I suspect we might assign different scale modes to different textures).

2021-06-07 02:30 UTC, flackr commented on CorsixTH/Src/th_gfx_sdl.cpp
> +    @return Enclosing SDL_Rect of the input rect scaled by scale_factor.
Oops, that was leftover from when it was the return value. Fixed.

2021-06-07 02:31 UTC, flackr commented
> This toggle is in a bit of a limbo as to whether it would support an in game toggle at the moment.
> 
> To do so:
> 
> * The SDL_SetHint for linear mode in `create` should be moved to an else condition of `if (direct_zoom)` in the `update` function of th_gfx_sdl.cpp.
> * global_scale_factor should be reset to 1.0
> * All textures would need to be flushed / recreated after the hint is changed. The documentation says that `SDL_HINT_RENDER_SCALE_QUALITY` is applied to a texture at creation rather than at copy (which explains why I didn't see any effect toggling it in set_scale_factor)
> 
> If we don't want it to be an in game toggle then this block belongs in the `create` function, either way we only want to set SDL_HINT_RENDER_SCALE_QUALITY in one place (for now - as the feature evolves I suspect we might assign different scale modes to different textures).

Sounds good. I've moved the flag to the create function as suggested. I'm assuming create only happens once so we should have zoom_texture == nullptr and global_scale_factor == 1.0 right? If not, I can reset them appropriately.

2021-06-07 03:20 UTC, TheCycoONE approved these changes

2021-06-07 03:22 UTC, TheCycoONE commented
> > This toggle is in a bit of a limbo as to whether it would support an in game toggle at the moment.
> > To do so:
> > 
> > * The SDL_SetHint for linear mode in `create` should be moved to an else condition of `if (direct_zoom)` in the `update` function of th_gfx_sdl.cpp.
> > * global_scale_factor should be reset to 1.0
> > * All textures would need to be flushed / recreated after the hint is changed. The documentation says that `SDL_HINT_RENDER_SCALE_QUALITY` is applied to a texture at creation rather than at copy (which explains why I didn't see any effect toggling it in set_scale_factor)
> > 
> > If we don't want it to be an in game toggle then this block belongs in the `create` function, either way we only want to set SDL_HINT_RENDER_SCALE_QUALITY in one place (for now - as the feature evolves I suspect we might assign different scale modes to different textures).
> 
> Sounds good. I've moved the flag to the create function as suggested. I'm assuming create only happens once so we should have zoom_texture == nullptr and global_scale_factor == 1.0 right? If not, I can reset them appropriately.

For completeness - yes it's only called once, immediately after the constructor.

2021-06-13 02:57 UTC, merged

2021-06-13 02:58 UTC, TheCycoONE commented
Since we are delaying, and this PR has been tested, I'm merging it in.

2021-06-13 04:18 UTC, flackr commented
Now that this is merged shall I file issues for the artifacts that would block making this the default rendering path?

2021-06-13 11:20 UTC, TheCycoONE commented
Yes please

2021-06-13 14:35 UTC, flackr commented
Done, filed #1929 and #1930 along with a rough idea of how I think they can be fixed.