Machine repair changes
CorsixTH/CorsixTH pull request #1988
Opened 2021-07-02 14:23 UTC by tobylane

**Describe what the proposed change does**
- Move the announcing function to PlayerHospital
- Add the handymen check per the comment

2021-07-02 19:53 UTC, lewri requested changes
We can ignore the lua failure

2021-07-02 19:53 UTC, lewri commented on CorsixTH/Lua/hospitals/player_hospital.lua
> +local AnnouncementPriority = _G["AnnouncementPriority"]
I would recommend always puttting this line at the top of the file before the class declaration. Also missing the ``require``

2021-07-02 19:53 UTC, lewri commented on CorsixTH/Lua/entities/machine.lua
>  corsixth.require("announcer")
As per other comment.
You don't need this line anymore if you're taking any announcements out of machine.

2021-07-05 11:06 UTC, lewri commented
I still think for the sake of uniformity you should re-add those require and announcementpriority lines into Player Hospital for now.
We can make a separate PR to test removing them across the board if the hunch of them not being required is right.

2021-07-05 12:19 UTC, tobylane commented
Agreed. Ready.

2021-07-05 12:47 UTC, lewri approved these changes

2021-07-06 01:29 UTC, merged