[RFC] Fix buffer overflow of played_sound_callbacks_ids
CorsixTH/CorsixTH pull request #2108
Opened 2022-02-24 23:09 UTC by mugmuggy

*Fixes #* 

**Describe what the proposed change does**
- Fix buffer overflow 
- Potentially addresses #1380, was also some older bugs (still bugs?) where lava hole spawns but not accessible by Grim, which would also accelerate the overflow as the lava hole stays spawned.

2022-02-25 17:28 UTC, lewri commented
Have you been able to test any of the possible affected bugs? I don't think we've had any sight of them in years so likely they were fixed or very rare.

2022-02-25 23:35 UTC, mugmuggy commented
Grim issue was resolved in #1708. There was another also resolved which was resolved I believe, kicking dying patients as they were on the way to lava hole. I've got the comment on #1380 about a crash with audio. I do recall the function which failed and seen that same buffer overflow cause the same access violation that I seen, but if it addresses 1380 or not I don't know. I think we've since silenced (?) announcements whilst paused, which is where I believe my crash was in 1380, and it was a silent crash to desktop on latest builds.

Its easy enough to replicate, spawn a lava hole through debug console, and you can monitor Audio:playSound for the value of
```lua
self.unused_played_callback_id = self.unused_played_callback_id + 1
```
This value will exceed 1000, get to somewhere else and then overwrites sound_player eventually. The do it twice thing from discord also makes getting to 1000+ quicker

2022-02-26 10:39 UTC, lewri commented
> I think we've since silenced (?) announcements whilst paused,

Announcements are halted now unless they had priority critical (so cheats usage was made known)

2022-03-03 03:29 UTC, TheCycoONE requested changes
We're moving to c++11 and standard container types where possible to prevent overflows. This is a good opportunity to do that instead.

2022-03-03 03:29 UTC, TheCycoONE commented on CorsixTH/Src/th_lua_sound.cpp
> +constexpr int max_callback_ids = 1000;
Prefer modernizing to std::array<int, 1000> played_sound_callback_ids;

2022-03-03 03:29 UTC, TheCycoONE commented on CorsixTH/Src/th_lua_sound.cpp
> +    if (played_sound_callback_index == max_callback_ids)
After making this a std::array, len can be used here.

2022-03-05 13:40 UTC, TheCycoONE approved these changes

2022-03-05 13:41 UTC, merged