Local hospital advice 3
CorsixTH/CorsixTH pull request #2155
Opened 2022-05-06 14:11 UTC by tobylane

**Describe what the proposed change does**
- Separate the VIP end fax into a PlayerHospital function
- Make more advice local hospital only
- Make machines use the local research progress

2022-05-14 03:43 UTC, TheCycoONE requested changes
minor changes, looks good

2022-05-14 03:43 UTC, TheCycoONE commented on CorsixTH/Lua/hospital.lua
> +function Hospital:makeVIPEndFax(vip_rating, name, cash_reward, vip_message)
Function above this uses Vip, this uses VIP - lets be consistent.

2022-05-17 18:31 UTC, lewri commented on CorsixTH/Lua/entities/humanoids/vip.lua
> +  self.last_hospital:makeVIPEndFax(self.vip_rating, self.name, self.cash_reward, self.vip_message)
Casing not updated here in line with hospital

2022-05-17 21:30 UTC, TheCycoONE approved these changes

2022-05-17 21:33 UTC, merged