Map editor menu improvement
CorsixTH/CorsixTH pull request #2206
Opened 2022-07-15 11:46 UTC by Matvey1705

**Describe what the proposed change does**
- Players can clear field, without leaving map editor and opening the map editor again
- Added options to map editor
- Players can overlay on map like v0.30 map editor (flags, parcel, positions) in options

2022-07-15 12:01 UTC, TheCycoONE requested changes
It would be cleaner to elevate the functions out of the game menu and reuse them here rather than copy/pasting the code.

I'm in favour of adding the options. The PR needs some refactoring.

2022-07-15 20:50 UTC, lewri commented
Just to say regardless thanks Matvey for looking at this! :)

2022-07-16 16:54 UTC, lewri requested changes
Still work to be done in the alignment here. Unfortunately that's made it a bit difficult to read where something starts and ends (namely `if app.audio.has_bg_music then`)

2022-07-16 16:54 UTC, lewri commented on CorsixTH/Lua/dialogs/menu.lua
> +	:appendItem(_S.menu_file.restart:format(hotkey_value_label("ingame_restartLevel", hotkeys)), function() app:mapEdit() end)
Indent slightly off with lines above and below here

2022-07-16 16:54 UTC, lewri commented on CorsixTH/Lua/dialogs/menu.lua
> +  local options = UIMenu()
This is already declared at line 546 (`local menu = UIMenu()`).

2022-07-16 16:54 UTC, lewri commented on CorsixTH/Lua/dialogs/menu.lua
> +          ""
This might be correct, but what are the "" for?

2022-07-16 16:54 UTC, lewri commented on CorsixTH/Lua/dialogs/menu.lua
> +    :appendItem(_S.menu_options.jukebox:format(hotkey_value_label("ingame_jukebox", hotkeys)), function() self.ui:addWindow(UIJukebox(app)) end)
```suggestion
  options:appendMenu(_S.menu_options.sound_vol, appendVolume("sound"))
    :appendMenu(_S.menu_options.music_vol, appendVolume("music"))
    :appendItem(_S.menu_options.jukebox:format(hotkey_value_label("ingame_jukebox", hotkeys)), function() self.ui:addWindow(UIJukebox(app)) end)
```

Sorry, never been keen on the excessive align for parts of the function params.

2022-07-16 16:54 UTC, lewri commented on CorsixTH/Lua/dialogs/menu.lua
> +  if app.audio.has_bg_music then
I can't easily see what line you `end` this if statement :(

2022-07-16 16:54 UTC, lewri commented on CorsixTH/Lua/dialogs/menu.lua
> +	)
Rid the alignment inside `appendMenu` and `appendCheckItem`

2022-07-16 16:54 UTC, lewri commented on CorsixTH/Lua/dialogs/menu.lua
> +end
Ack :(

2022-07-16 16:54 UTC, lewri commented on CorsixTH/Lua/dialogs/menu.lua
> +    :appendItem(_S.menu_options.jukebox:format(hotkey_value_label("ingame_jukebox", hotkeys)), function() self.ui:addWindow(UIJukebox(app)) end)
To note: 608 could be split across two lines but that's a smaller issue and one that can be left for now.

2022-07-20 20:21 UTC, TheCycoONE commented
Do you mind if I fix this up @Matvey1705

2022-08-15 19:38 UTC, TheCycoONE commented
No response, cannot merge as is.

2023-04-18 07:58 UTC, Matvey1705 commented
> Do you mind if I fix this up @Matvey1705


Its too, too late, if you still can do this please do it. Was checking notifications and found this. Sorry about that

2023-04-19 16:05 UTC, lewri commented
Reopened at request from discord/matrix

2023-09-30 10:23 UTC, tobylane commented
I've rebased, refactored, altered whitespace.

Should the restart map menu option have a confirm window?

2023-12-30 10:32 UTC, tobylane commented
A whitespace fix, and a rebase. The map editor restart confirm window will come later.

Ready.

2023-12-30 13:37 UTC, Alberth289346 commented on CorsixTH/Lua/dialogs/menu.lua
> +  local hotkeys = app.hotkeys
- Add an empty line above this line. 

  The first line handles something else than this and the next lines. If you add an empty line between such blocks, you can find closely related code for some part more easily.

  Also, it helps in navigating. When looking for some specific part, you can start reading code and when you realize it's not what you are looking for, you can simply skip to code below the next empty line. You don't need to carefully keep reading to find the spot where the code starts doing something else.

  One step further, if you would start each such block with a single line of comment that describes what the code block is doing, you can navigate even quicker by reading the comment line, decide if the code block is what you're looking for, and if not directly skip to the next block with the next comment line above it.

- You don't seem to need `hotkeys` until further down in the function, so move that line closer to first use.

2024-01-04 19:45 UTC, lewri commented
@tobylane can you just re-summarise what this PR is now doing as I guess its nature has changed.

You should also be able to add an 'Edit' note to the OP's post at the bottom with this.

>Should the restart mapeditor menu option have a confirm window?
Although you're now doing this later, yes it definitely should.

2024-03-18 22:04 UTC, lewri commented
Are we good to merge this? I see no issue.

@tobylane does this need a rebase first? I don't think it does...

2024-03-21 02:54 UTC, merged