Fix for: Deactivate epidemics cheat doesn't work.
CorsixTH/CorsixTH pull request #2753
Opened 2024-12-28 10:20 UTC by ARGAMX

*Fixes #2718*

**Describe what the proposed change does**
- Fixed a bug due to which epidemics cheat doesn't work.
- Also added cancelation for any already preparing epidemics.
- Also added cancelation for any already ongoing epidemic:
- - Turn vaccination mode off if enabled.
- - Remove epidemic timer if visible.
- - Send inspector home if spawned.
- - Clear epidemic patients.
- - Remove epidemic discovered fax from bottom_panel if fax pending to open.
- Fax `owner` now can be not only `humanoid`, but any object, as `epidemic`.

2025-01-02 18:01 UTC, tobylane approved these changes
The check removed in `Cheats:cheatEpidemic` could be remade as below, but it's not important. Looks good, plays right.

```lua
function Hospital:spawnContagiousPatient()
  if self.epidemics_disabled then return false, _S.misc.epidemics_off end
```

2025-01-04 06:57 UTC, ARGAMX commented
> The check removed in `Cheats:cheatEpidemic` could be remade as below, but it's not important. Looks good, plays right.
> 
> ```lua
> function Hospital:spawnContagiousPatient()
>   if self.epidemics_disabled then return false, _S.misc.epidemics_off end
> ```

I thought about it, but I have not found any reasonable benefits for this condition. 

If add this condition then it's possible that the user press that button and tries to generate an infectious patient, but it doesn't generates. Then it looks like the cheat don't work. (bug)

It seems like if the user turns off epidemics, it means that he doesn't want the game to generate epidemics itself. Not that the game should block his ability to create an epidemic himself. (For what?)

2025-01-21 19:11 UTC, lewri commented on CorsixTH/Lua/hospital.lua
> +  self.epidemics_disabled = false
As a general note, this declaration isn't needed; since nil also equals false for a boolean check. We also don't pre-assign a value to `hospital.cheated` or `world.earthquake.disabled`.
Old saves will still use nil anyway.

2025-01-21 21:00 UTC, lewri requested changes

2025-01-21 21:00 UTC, lewri commented on CorsixTH/Lua/cheats.lua
> +  return self.hospital:spawnContagiousPatient()
We're now generating a contagious patient even when we set epidemics to be disabled? Ah no, please don't do that.

Toby's suggestion passes the failure reason across to the player as a UIInformation dialog. They do receive feedback:
https://github.com/CorsixTH/CorsixTH/blob/b2fe51272b46d43911cb1886e8d4a5c086205e5c/CorsixTH/Lua/dialogs/resizables/cheats_dialog.lua#L130-L144
As an example of what the player will see:
![image](https://github.com/user-attachments/assets/4cf49533-abbb-44fc-bd51-4442436d2710)

2025-01-22 08:12 UTC, ARGAMX commented on CorsixTH/Lua/hospital.lua
> +  self.epidemics_disabled = false
> As a general note, this declaration isn't needed; since nil also equals false for a boolean check. We also don't pre-assign a value to `hospital.cheated` or `world.earthquake.disabled`. Old saves will still use nil anyway. Read: Not important -- just a nit

True. 👌
Yes, I understand.
But I wanted to add a comment to this flag. What it is and what it is for.
So I had to add an declaration here.

2025-01-23 17:34 UTC, ARGAMX commented on CorsixTH/Lua/cheats.lua
> +  return self.hospital:spawnContagiousPatient()
Oh, Lewri thank you very much.
The screenshot was very helpful.
I really didn't understand Toby suggesting.
This is really much better. 👍

2025-01-23 18:43 UTC, lewri approved these changes

2025-01-23 18:44 UTC, merged